#pragma once

enum {
  WORKER_KEY_TRICORDER_START,
  WORKER_KEY_TRICORDER_STOP,
  WORKER_KEY_TRICORDER_TOGGLE,
  WORKER_KEY_TRICORDER_RESET,
  WORKER_KEY_TRICORDER_UPDATE,
};

enum {
  PERSIST_KEY_IS_LOGGING = 100,
};
